import type { Metadata } from "next";
import "./globals.css";
import { Audio } from "@/constants/audio";
import BackgroundOverlay from "@/components/background/overlay";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-image bg-cover bg-center h-screen bg-no-repeat">
        <BackgroundOverlay src={Audio.INTRO} />
        {children}
      </body>
    </html>
  );
}
