import type { Metadata } from 'next';
import './globals.css';
import BackgroundOverlay from '@/components/background/overlay';
import { Toaster } from '@/components/ui/sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-image bg-cover bg-center h-screen bg-no-repeat flex justify-center">
        <BackgroundOverlay />
        <Toaster />
        {children}
      </body>
    </html>
  );
}
